### ISSUE TITLE
remove global styling for MUI components

### ISSUE THREAD

**Issue by lennczar** [near-multicall/ui#190]
`TextField` styling on the DAO page is different from the styling we use on the App page, this is fine so long the styling on the App page is not affected. However, CSS rules introduced in [settings-editor-amendments](https://github.com/near-multicall/ui/tree/settings-editor-amendments) in `src/app/global.scss` do affect it.

Example: fields of UnitField are no longer the same height
![image](https://user-images.githubusercontent.com/42617542/214105838-1f4028f0-fa66-4ffe-b8be-0a31bf856dd9.png)

Please remove these rules and move them to local styling:
```scss
.MuiCheckbox-root {
    .MuiSvgIcon-root {
        width: size.$large-text;
        height: size.$large-text;
    }
}

.MuiTextField-root {
    .MuiInputLabel-root,
    .MuiInputBase-root {
        font-size: size.$text;

        input {
            padding: calc(size.$gap * 0.4) calc(size.$gap * 0.6);
            font-size: size.$text;
        }

        fieldset {
            border-radius: size.$task-radius;
        }
    }
}
```
